import "./globals.css";
import Header from "./Components/main-header/page";

export const metadata = {
  title: "Food App",
  description: "Generated by create next app",
  icons: {
    icon: "/next.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
